### ISSUE TITLE
Update build documentation for Mac

### ISSUE THREAD

**Issue by karkar** [fogies/web-jayfo#99] opened 2016-01-11 20:03 UTC
- Python version doesn't seem to be an issue as of yet (2.7 or 3.4/3.5) : if you want to avoid using multiple versions and setting up virtual env every time you want to build the site. 
- Ruby version should be 2.2.x, I was running 2.0.x and 'invoke' would run fine without throwing errors, but would not spin up a server
- There is no 'ruby devkit' for mac, so I ignored that step
- Virutalizations are slightly different in python 2.7 and 3.4, commands have changed (virtualenv vs pyvenv)
    - If using virtualization in python, the activation path will be 'env35/bin/activate'

**Comment by karkar** [comment] 2016-01-12 10:00
https://github.com/fogies/web-jekyll-base/issues/42 This is a more detailed version.

**Comment by jayfo** [comment] 2016-01-16 18:13
Duplicate of https://github.com/fogies/web-jekyll-base/issues/42

**Closed by jayfo** 2016-01-16 18:13 UTC
